apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: example-secret-generator
files:
  - ./secret-test-encrypted.yaml
# TODO noch besser: https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#generate-secret-directly-from-encrypted-files
