creation_rules:
- kms: 'arn:aws:kms:eu-central-1:674579165179:key/6fd6fef5-8265-4235-97b5-1da4ed01b92b' # k8s_secrets mit IAM dev_k8s_secrets_deploy
  path_regex: '(.*)(-encrypted|-unencrypted)\.yaml'
