apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - ../../base

helmGlobals:
  chartHome: ..

generators:
  - ./secret-generator.yaml

helmCharts:
  - name: helm
    version: v1.0.0
    releaseName: test-aws-kms
    namespace: wbnextgen-dev
    valuesFile: ../helm/values.yaml
    additionalValuesFiles:
      - ../helm/values-dev.yaml
